### ISSUE TITLE
Pointer to the SoftSlowI2CMaster Wire Wrapper

### ISSUE THREAD

**Issue by mwachs5** [felias-fogg/SlowSoftI2CMaster#1]
Excited to use this for our project. Can you please point me to the Wrapper class that you mention in the README, to use the SoftSlowI2CMaster interface to emulate the Wire interface?

**Comment by felias-fogg** [comment]
It is the library SlowSoftWire in my repository: https://github.com/felias-fogg/SlowSoftWire

Note that it is brand new and may contain bugs. I have tested it with the examples only. Good luck!

**Comment by felias-fogg** [comment]
Added in the readme files and in the Playground description.
