### ISSUE TITLE
License type?

### ISSUE THREAD

**Issue by stawel** [felias-fogg/SlowSoftI2CMaster#2]
Hi, 
I just made a fork of your code,
and I'm wondering if I'm allowed to?

Best Regards,
Paweł

**Comment by felias-fogg** [comment]
Sure! Go ahead.

If you fix a bug or add functionality, tell me. Then I will reintegrate it.

Best
Bernhard

**Comment by stawel** [comment]
Thanks! 

> If you fix a bug or add functionality, tell me. Then I will reintegrate it.

I'm not sure if it's something worth mentioning, since my modifications is out of the scope of
the I2C specification:
https://github.com/stawel/SlowSoftI2CMaster/commit/0d9fa5067128a54e747a90de7e6b8ba8aa8fe01e
It allows you to communicate without the mandatory bus resistors.

**Comment by felias-fogg** [comment]
Thanks,

why do you say it is outside the I2C spec? It uses the internal pull-up resistors instead of providing external ones. I guess this is feasible. The only problem might be that the internal resistors may have a value that is too high (20-50K on an ATmega328) to support the desired rise time. This, however depends on the bus capacistance and the bus frequency (see e.g. www.ti.com/lit/an/slva689/slva689.pdf). 

Did you have also a quick look with a scope what is happening on the bus? 

Cheers 
Bernhard

**Comment by stawel** [comment]
> Did you have also a quick look with a scope what is happening on the bus?

unfortunately I don't own a scope :/
but I viewed the signals of my wt150 3d printer:
http://beta.ivc.no/wiki/images/9/95/MakerBot_Replicator_Mightyboard_RevE_Schematic.png
atmega1280, pins 68, 94, 90, 86 (POTS-SCL, X-AXIS-POT, Y-AXIS-POT, Z-AXIS-POT)
on a logic analyzer and it worked - the printer does not  have the external bus resistors by design.

**Comment by cfobel** [comment]
Thanks @felias-fogg so much for sharing your great work!

Would you please consider explicitly adding a license to this project (and [`felias-fogg/SlowSoftWire`][0])?

Might I suggest the LGPL?  It is used for [all code in the Arduino project][2] (including the mainline [`Wire` library][1]).  This would allow your code to be used as a drop-in replacement for any projects using the [`Wire` library][1].  Note that the LGPL requires that any modifications made to the source code of your library to be shared, ensuring that you benefit from any bug fixes or improvements.

Thanks again!

[0]: https://github.com/felias-fogg/SlowSoftWire
[1]: https://github.com/arduino/Arduino/blob/master/hardware/arduino/avr/libraries/Wire/src/Wire.h
[2]: https://www.arduino.cc/en/Main/FAQ

**Comment by felias-fogg** [comment]
License (LGPL) added and integrated the possibility to use internal pullups.

**Comment by cfobel** [comment]
Thanks for adding the license terms!
